### ISSUE TITLE
Zigbee logging

### ISSUE THREAD

**Issue by TheArcturian** [irritanterik/homey-realtime-logpage#11]
Is there any chance to see what's going on in the Zigbee mesh? According to Athom, some of my Zigbee devices are spamming Homey and delaying the whole system. However there is no tools that I can find that can show Zigbee traffic just like Z-Wave traffic.

Any chance you will implement that?

**Comment by irritanterik** [comment]
Can you try my concept index.html? Don't have zigbee myself, but it could be working :)

**Comment by TheArcturian** [comment]
Yeah, I have, but can't see anything about Zigbee devices getting logged there. You have created a great tool by the way. I discovered a small issue because of it, so good job with it!

I just saw a checkbox for zwave so I was hoping it maybe was an easy fix to add zigbee logging as well. Though, it is Athom that should fix that by the way. ;-)

**Comment by irritanterik** [comment]
Have you tested it with the zigbee checkbox checked?

**Comment by TheArcturian** [comment]
I'm still running 1.5.13 (because of the desktop software). Should it still work there? It just says "Starting log...", but nothing gets listed.

**Comment by irritanterik** [comment]
No, 1.5.x is not supported.

**Comment by TheArcturian** [comment]
Ok. Will check when I've upgraded sometime in the future.
