### ISSUE TITLE
Incorrect delay shown in flow viewer

### ISSUE THREAD

**Issue by Fire69** [irritanterik/homey-realtime-logpage#13]
Hey,

Just noticed that delays in the flow viewer are shown in seconds while they are set as minutes in the app.
![image](https://user-images.githubusercontent.com/1757287/52203253-1a598280-2871-11e9-856e-0af1a0105e44.png)

![screenshot_20190204-113637_homey](https://user-images.githubusercontent.com/1757287/52203386-699fb300-2871-11e9-9841-6e1278537fcd.jpg)

Homey v2.0.2
Flow viewer: version from 03/02/2018

**Comment by irritanterik** [comment]
Thanks! Must be a bug here: https://github.com/irritanterik/homey-realtime-logpage/blob/master/flowview.html#L372 
Will look at it tonight.

**Comment by irritanterik** [comment]
Fixed with 0e4080526397d6f6e53fc4849cb5c8beedaeec0a
