### ISSUE TITLE
FLOW VIEWER stuck at "making Homey great again"

### ISSUE THREAD

**Issue by viixxiiv** [irritanterik/homey-realtime-logpage#17]
Thanks for the great function! I use the flow viewer alot to search for variables and linked flows as the web flow editor doesn't support searching.
But recently with the athom changes, I can no longer use this.
The loading screen gets stuck at "making Homey great again". Only workaround at the moment is to "print to pdf" and search with acrobat. For there I can see that all the flows appears to be present, so somehow something is screwing with the
showLoading('making Homey great again')
    showFlows()

**Comment by irritanterik** [comment]
fixed
