### ISSUE TITLE
bearer token

### ISSUE THREAD

**Issue by eriklenaerts** [irritanterik/homey-realtime-logpage#2]
Hey,

trying to get this up, however, when I go to my.athom.com, login and select the homey and then go to the console it says undefined for window.bearer_token. Any ideas?

thnx

**Comment by irritanterik** [comment]
Hi Erik,
Maybe something changed. You can work around this by getting the bearer from an authorized request.
Just open the details of a device and catch the request on the network tab:

![image](https://cloud.githubusercontent.com/assets/15232724/20683800/b0252ffa-b5ad-11e6-9e96-f1426e606615.png)

**Comment by eriklenaerts** [comment]
ok, found the bearer token. So, I started the index.html (using brackets) which fire up a local server. Then I create a flow and perform a simple HTTP Get to http://httpbin.org/. 

Should I then see something popping up in the realtime log page?

**Comment by irritanterik** [comment]
Yes:
![image](https://cloud.githubusercontent.com/assets/15232724/20687455/c75ff95c-b5bc-11e6-9a8e-21018787074e.png)

**Comment by eriklenaerts** [comment]
I installed the HTTP request flow from the app store, perhaps I should grab the one from github and run it via the commandline using athom project --run?
