### ISSUE TITLE
no issue

### ISSUE THREAD

**Issue by qwerk** [irritanterik/homey-realtime-logpage#3]
HI,  there is no issue, but I could not find a way to contact you. sorry.

Is it possible that the index.html get's the ip address and bearer token from an ini file orso?
Then we/I can update without having to edit it.

thanks in advance.

Aren

**Comment by irritanterik** [comment]
Thanks for your suggestion. I added this now. Just setup your settings in config.js once and only download the index.html or flowview.html.
