### ISSUE TITLE
Not compatible with Homey firmware 1.2.x

### ISSUE THREAD

**Issue by jghaanstra** [irritanterik/homey-realtime-logpage#6]
It seems the Flow Viewer is not compatible with Homey firmware 1.2.x. After upgrading I'm getting the flowing javascript error breaking the functionality on the page.

`Uncaught TypeError: Cannot read property 'label' of undefined
    at formatArgValue (http://192.168.0.110/homey-realtime-logpage/flowview.html:297:66)
    at http://192.168.0.110/homey-realtime-logpage/flowview.html:284:47
    at Array.forEach (native)
    at formatArgs (http://192.168.0.110/homey-realtime-logpage/flowview.html:282:28)
    at formatCard (http://192.168.0.110/homey-realtime-logpage/flowview.html:259:77)
    at http://192.168.0.110/homey-realtime-logpage/flowview.html:240:23
    at Array.forEach (native)
    at formatCards (http://192.168.0.110/homey-realtime-logpage/flowview.html:239:16)
    at addFlow (http://192.168.0.110/homey-realtime-logpage/flowview.html:215:51)
    at flows.forEach.flow (http://192.168.0.110/homey-realtime-logpage/flowview.html:409:7)
`

**Comment by jghaanstra** [comment]
Hmm, I had only added on flow after upgrading to 1.2.x and after deleting this flow and trying again it works. There is something with the iKettle action card that is causing this issue. Closed for now.

**Comment by irritanterik** [comment]
If looked at the iKettle app.json but this looks ok. Please include the response of GET http://[homey local ip]/api/manager/flow/flow/[flowid as seen in floweditor] here if this issue occurs again.

**Comment by jghaanstra** [comment]
Hi Erik,

This is not yours to solve so dont put to much effort into it. Below the response for this specific flow.

`
"id":"some_id",
"title":"Stem: water koken",
"enabled":true,
"folder":"some_id",
"order":3,
"broken":false,
"trigger":{
"id":"said",
"uri":"homey:manager:speech-input",
"args":{
},
"droptoken":false
},
"conditions":[
{
"id":"contains",
"uri":"homey:manager:logic",
"args":{
"comparator":"koken"
},
"droptoken":"speech",
"inverted":false
}
],
"actions":[
{
"id":"ikettle2_on",
"uri":"homey:device:some_id",
"args":{
"temperature":100,
"keep_warm":"false"
},
"droptoken":false,
"delay":{
"number":"0",
"multiplier":"1"
},
"duration":false
},
{
"id":"say",
"uri":"homey:manager:speech-output",
"args":{
"text":"He ketel, ga eens koken!"
},
"droptoken":false,
"delay":{
"number":"0",
"multiplier":"1"
},
"duration":false
},
{
"id":"show_animation",
"uri":"homey:manager:ledring",
"args":{
"animation":"colorwipe",
"color":"#93ff00"
},
"droptoken":false,
"delay":{
"number":"2",
"multiplier":"1"
},
"duration":false
}
]
}
`

**Comment by irritanterik** [comment]
https://github.com/athombv/am.smarter/issues/8

**Comment by jghaanstra** [comment]
Thanx!

**Comment by irritanterik** [comment]
Probably fixed with ea43c0b

**Comment by jghaanstra** [comment]
Confirmed!

Thank you once again ...
