### ISSUE TITLE
Flow Viewer - Folders and search not working anymore

### ISSUE THREAD

**Issue by Fire69** [irritanterik/homey-realtime-logpage#7]
Hey,

It's been a while since I used the flow viewer and I just noticed folders and search are not working anymore.
Maybe caused by firmware upgrade? (I'm on 1.3.0rc7)

![image](https://cloud.githubusercontent.com/assets/1757287/26697676/2bebe344-4713-11e7-8904-7957534c6fdf.png)

**Comment by irritanterik** [comment]
Well, it's been a while since I checked this, but today I pushed a new version.
